### ISSUE TITLE
sfdx.org.create support

### ISSUE THREAD

**Issue by wadewegner** [coveo/sfdx-js#2]
Having an issue getting `sfdx.org.create( ...` working now. Seemed like it was working in an earlier build, and I was seeing all the supported parameters.

**Comment by marcantoineveilleux** [comment]
Are you talking about the auto-completion or the function in itself?

If it's the auto-completion, seems like the new way to bundle lacks something. I'll investigate.

**Comment by wadewegner** [comment]
I suspect just the auto-completion.

**Comment by marcantoineveilleux** [comment]
I am able to reproduce, seems like VSCode doesn't like default module export. Trying to find a solution.

**Comment by marcantoineveilleux** [comment]
I've changed back to named export instead of using default export.

This is a breaking change. Please use `var sfdx = require('sfdx-js').Client.createUsingPath('sfdx')` to instantiate the client.
